name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  minimal-test:
    uses: blazonui/blazonui-workflows/.github/workflows/minimal4.yml@main
    with:
      curseforge-id: "1656841"
      wago-id: "b6XeOOKp"
