name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: blazonui/blazonui-workflows/.github/workflows/release-addon.yml@main
    with:
      curseforge-id: "1656841"
      wago-id: "b6XeOOKp"
